export const WorkQueueData = [
  // Original 6
  {
    id: 1,
    originator: 'Sam Masters',
    client: 'NAMEX Tech Solutions',
    line: 'Cyber Liability',
    type: 'Underwriter Referral',
    status: 'New',
    created: '2025-04-16T00:00:00Z',
  },
  {
    id: 2,
    originator: 'Annalise Willis',
    client: 'Maritime Logistics Corp',
    line: 'Marine Cargo',
    type: 'Underwriter Referral',
    status: 'New',
    created: '2025-04-20T00:00:00Z',
  },
  {
    id: 3,
    originator: 'Patrick Devenport',
    client: 'GreenField Energy Ltd',
    line: 'Environmental',
    type: 'Loss Control Request',
    status: 'New',
    created: '2025-04-16T00:00:00Z',
  },
  {
    id: 4,
    originator: 'Ana Killian',
    client: 'NorthStar Financial Group',
    line: 'D&O Liability',
    type: 'Underwriter Referral',
    status: 'Pending Review',
    created: '2025-04-22T00:00:00Z',
  },
  {
    id: 5,
    originator: 'Ana Killian',
    client: 'Alliance Healthcare Systems',
    line: 'Medical Malpractice',
    type: 'Email',
    status: 'Completed',
    created: '2025-04-28T00:00:00Z',
  },
  {
    id: 6,
    originator: 'Me',
    client: 'QuantumTech Industries',
    line: 'Product Liability',
    type: 'Email',
    status: 'Completed',
    created: '2025-04-20T00:00:00Z',
  },

  // 6 with status: 'Referral'
  {
    id: 7,
    originator: 'Jason Lee',
    client: 'Titan Insurance Co.',
    line: 'General Liability',
    type: 'Referral Follow-up',
    status: 'Referral',
    created: '2025-05-01T00:00:00Z',
  },
  {
    id: 8,
    originator: 'Laura Chen',
    client: 'EcoBuild Corp',
    line: 'Construction Liability',
    type: 'Underwriter Referral',
    status: 'Referral',
    created: '2025-05-02T00:00:00Z',
  },
  {
    id: 9,
    originator: 'Carlos Diaz',
    client: 'Skyline Apartments',
    line: 'Property',
    type: 'Referral Submission',
    status: 'Referral',
    created: '2025-05-03T00:00:00Z',
  },
  {
    id: 10,
    originator: 'Sandra Mills',
    client: 'NextGen Labs',
    line: 'Cyber Liability',
    type: 'Loss Control Request',
    status: 'Referral',
    created: '2025-05-04T00:00:00Z',
  },
  {
    id: 11,
    originator: 'Tom Becker',
    client: 'SafeHarbor Systems',
    line: 'Marine Cargo',
    type: 'Email',
    status: 'Referral',
    created: '2025-05-05T00:00:00Z',
  },
  {
    id: 12,
    originator: 'Diana Wong',
    client: 'MediSecure Ltd',
    line: 'Medical Malpractice',
    type: 'Email',
    status: 'Referral',
    created: '2025-05-06T00:00:00Z',
  },

  // 6 with status: 'Pending Review'
  {
    id: 13,
    originator: 'Grace Patel',
    client: 'Global Freight Inc',
    line: 'Marine Cargo',
    type: 'Underwriter Referral',
    status: 'Pending Review',
    created: '2025-05-07T00:00:00Z',
  },
  {
    id: 14,
    originator: 'Marcus Reed',
    client: 'SecureBank',
    line: 'Financial Institutions',
    type: 'Loss Control Request',
    status: 'Pending Review',
    created: '2025-05-08T00:00:00Z',
  },
  {
    id: 15,
    originator: 'Emily Tran',
    client: 'Biotech Ventures',
    line: 'Life Sciences',
    type: 'Email',
    status: 'Pending Review',
    created: '2025-05-09T00:00:00Z',
  },
  {
    id: 16,
    originator: 'James Foley',
    client: 'UrbanEdge Realty',
    line: 'Property',
    type: 'Email',
    status: 'Pending Review',
    created: '2025-05-10T00:00:00Z',
  },
  {
    id: 17,
    originator: 'Tina Zhang',
    client: 'HealthFirst Co.',
    line: 'Medical Malpractice',
    type: 'Referral Follow-up',
    status: 'Pending Review',
    created: '2025-05-11T00:00:00Z',
  },
  {
    id: 18,
    originator: 'Robert Ellis',
    client: 'AutoSure Ltd',
    line: 'Automobile Liability',
    type: 'Underwriter Referral',
    status: 'Pending Review',
    created: '2025-05-12T00:00:00Z',
  },
];

export const WorkQueueDisplayColumns: string[] = [
  'originatorInfo',
  'clientLine',
  'type',
  'status',
  'created',
  'actions',
];

export const MyAccountsData = [
  {
    id: 1,
    accountName: 'NAMEX Tech Solutions',
    type: 'Large Enterprise',
    line: 'D&O Liability',
    broker: 'Willis Towers',
    renewalDate: '2025-04-16T00:00:00Z',
    premium: '$2.3M',
    ratedPremium: '$2.8M',
    lossRatio: '32%',
    appetite: 'HIGH',
    status: 'Active',
    triage: 180,
    winnability: 'Very Strong',
  },
  {
    id: 2,
    accountName: 'Alliance Healthcare Systems',
    type: 'Mid-Market',
    line: 'Medical Malpractice',
    broker: 'Aon Risk',
    renewalDate: '2025-06-30T00:00:00Z',
    premium: '$1.7M',
    ratedPremium: '$1.9M',
    lossRatio: '38%',
    appetite: 'MEDIUM',
    status: 'Under review',
    triage: 165,
    winnability: 'Strong',
  },
  {
    id: 3,
    accountName: 'Maritime Logistics Corp',
    type: 'Shipping/Logistics',
    line: 'Marine Cargo',
    broker: 'Marsh McLennan',
    renewalDate: '2025-09-05T00:00:00Z',
    premium: '$875K',
    ratedPremium: '$920K',
    lossRatio: '25%',
    appetite: 'HIGH',
    status: 'Active',
    triage: 182,
    winnability: 'Very Strong',
  },
  {
    id: 4,
    accountName: 'GreenField Energy Ltd',
    type: 'Energy Sector',
    line: 'Environmental Liability',
    broker: 'Aon Risk',
    renewalDate: '2025-07-22T00:00:00Z',
    premium: '$1.2M',
    ratedPremium: '$1.4M',
    lossRatio: '67%',
    appetite: 'CAUTIOUS',
    status: 'Under review',
    triage: 158,
    winnability: 'Medium',
  },
];

export const MyAccountDisplayColumns: string[] = [
  'accountNameType',
  'line',
  'broker',
  'renewalDate',
  'premium',
  'ratedPremium',
  'lossRatio',
  'appetite',
  'status',
  'triage',
  'winnability',
  'actions',
];
